const _products = [
  {
    id: 1,
    name: 'チェスターコート',
    src: require('@/assets/outer-women/outer-women-item1.jpg'),
    gender: 'women',
    itemCategory: 'アウター',
    price: '3980',
    quantity: 1,
  },
  {
    id: 2,
    name: 'ボアフリースブルゾン',
    src: require('@/assets/outer-women/outer-women-item2.jpg'),
    gender: 'women',
    itemCategory: 'アウター',
    price: '4980',
    quantity: 1,
  },
  {
    id: 3,
    name: 'ステンカラーコート',
    src: require('@/assets/outer-women/outer-women-item3.jpg'),
    gender: 'women',
    itemCategory: 'アウター',
    price: '1980',
    quantity: 1,
  },
  {
    id: 4,
    name: 'ポケッタブルパーカ',
    src: require('@/assets/outer-women/outer-women-item4.jpg'),
    gender: 'women',
    itemCategory: 'アウター',
    price: '2980',
    quantity: 1,
  },
  {
    id: 5,
    name: 'レザージャケット',
    src: require('@/assets/outer-women/outer-women-item5.jpg'),
    gender: 'women',
    itemCategory: 'アウター',
    price: '3980',
    quantity: 1,
  },
  {
    id: 6,
    name: 'ブロックテックコート',
    src: require('@/assets/outer-women/outer-women-item6.jpg'),
    gender: 'women',
    itemCategory: 'アウター',
    price: '4980',
    quantity: 1,
  },
  {
    id: 7,
    name: 'オーバーオールジーンズ',
    src: require('@/assets/pants-women/pants-women-item1.jpg'),
    gender: 'women',
    itemCategory: 'ボトムス',
    price: '4980',
    quantity: 1,
  },
  {
    id: 8,
    name: 'ショートジーンズパンツ',
    src: require('@/assets/pants-women/pants-women-item2.jpg'),
    gender: 'women',
    itemCategory: 'ボトムス',
    price: '4980',
    quantity: 1,
  },
  {
    id: 9,
    name: 'ストレッチスカート',
    src: require('@/assets/pants-women/pants-women-item3.jpg'),
    gender: 'women',
    itemCategory: 'ボトムス',
    price: '4980',
    quantity: 1,
  },
  {
    id: 10,
    name: 'ワイドジーンズパンツ',
    src: require('@/assets/pants-women/pants-women-item4.jpg'),
    gender: 'women',
    itemCategory: 'ボトムス',
    price: '4980',
    quantity: 1,
  },
  {
    id: 11,
    name: 'プリーツミニスカート',
    src: require('@/assets/pants-women/pants-women-item5.jpg'),
    gender: 'women',
    itemCategory: 'ボトムス',
    price: '4980',
    quantity: 1,
  },
  {
    id: 12,
    name: 'シフォンロングスカート',
    src: require('@/assets/pants-women/pants-women-item6.jpg'),
    gender: 'women',
    itemCategory: 'ボトムス',
    price: '4980',
    quantity: 1,
  },
  {
    id: 13,
    name: 'オーバージャケット',
    src: require('@/assets/outer-men/outer-men-item1.jpg'),
    gender: 'men',
    itemCategory: 'アウター',
    price: '2980',
    quantity: 1,
  },
  {
    id: 14,
    name: 'ライトレザージャケット',
    src: require('@/assets/outer-men/outer-men-item2.jpg'),
    gender: 'men',
    itemCategory: 'アウター',
    price: '2980',
    quantity: 1,
  },
  {
    id: 15,
    name: 'モッズコート',
    src: require('@/assets/outer-men/outer-men-item3.jpg'),
    gender: 'men',
    itemCategory: 'アウター',
    price: '2980',
    quantity: 1,
  },
  {
    id: 16,
    name: 'デニムジャケット',
    src: require('@/assets/outer-men/outer-men-item4.jpg'),
    gender: 'men',
    itemCategory: 'アウター',
    price: '2980',
    quantity: 1,
  },
  {
    id: 17,
    name: 'スエットプルパーカ',
    src: require('@/assets/outer-men/outer-men-item5.jpg'),
    gender: 'men',
    itemCategory: 'アウター',
    price: '2980',
    quantity: 1,
  },
  {
    id: 18,
    name: 'レザージャケット',
    src: require('@/assets/outer-men/outer-men-item6.jpg'),
    gender: 'men',
    itemCategory: 'アウター',
    price: '2980',
    quantity: 1,
  },
  {
    id: 19,
    name: 'ドライウェットパンツ',
    src: require('@/assets/pants-men/pants-men-item1.jpg'),
    gender: 'men',
    itemCategory: 'ボトムス',
    price: '2980',
    quantity: 1,
  },
  {
    id: 20,
    name: 'スキニーフィットチノ',
    src: require('@/assets/pants-men/pants-men-item2.jpg'),
    gender: 'men',
    itemCategory: 'ボトムス',
    price: '2980',
    quantity: 1,
  },
  {
    id: 21,
    name: 'ストレッチジーンズ',
    src: require('@/assets/pants-men/pants-men-item3.jpg'),
    gender: 'men',
    itemCategory: 'ボトムス',
    price: '2980',
    quantity: 1,
  },
  {
    id: 22,
    name: 'ボアスウェットパンツ',
    src: require('@/assets/pants-men/pants-men-item4.jpg'),
    gender: 'men',
    itemCategory: 'ボトムス',
    price: '2980',
    quantity: 1,
  },
  {
    id: 23,
    name: 'スキニージーンズ',
    src: require('@/assets/pants-men/pants-men-item5.jpg'),
    gender: 'men',
    itemCategory: 'ボトムス',
    price: '2980',
    quantity: 1,
  },
  {
    id: 24,
    name: 'ヴィンテージチノ',
    src: require('@/assets/pants-men/pants-men-item6.jpg'),
    gender: 'men',
    itemCategory: 'ボトムス',
    price: '2980',
    quantity: 1,
  },
  {
    id: 25,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'kids',
    itemCategory: 'アウター',
    price: '0',
    quantity: 0,
  },
  {
    id: 26,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'kids',
    itemCategory: 'ボトムス',
    price: '0',
    quantity: 0,
  },
  {
    id: 27,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'kids',
    itemCategory: 'セーター',
    price: '0',
    quantity: 0,
  },
  {
    id: 28,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'kids',
    itemCategory: 'シャツ',
    price: '0',
    quantity: 0,
  },
  {
    id: 29,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'kids',
    itemCategory: 'インナー',
    price: '0',
    quantity: 0,
  },
  {
    id: 30,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'kids',
    itemCategory: 'グッズ',
    price: '0',
    quantity: 0,
  },
  {
    id: 31,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'women',
    itemCategory: 'セーター',
    price: '0',
    quantity: 0,
  },
  {
    id: 32,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'women',
    itemCategory: 'インナー',
    price: '0',
    quantity: 0,
  },
  {
    id: 33,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'women',
    itemCategory: 'シャツ',
    price: '0',
    quantity: 0,
  },
  {
    id: 34,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'women',
    itemCategory: 'グッズ',
    price: '0',
    quantity: 0,
  },
  {
    id: 35,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'men',
    itemCategory: 'セーター',
    price: '0',
    quantity: 0,
  },
  {
    id: 36,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'men',
    itemCategory: 'インナー',
    price: '0',
    quantity: 0,
  },
  {
    id: 37,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'men',
    itemCategory: 'シャツ',
    price: '0',
    quantity: 0,
  },
  {
    id: 38,
    name: '新商品をお待ちください',
    src: require('@/assets/others/noimege.jpg'),
    gender: 'men',
    itemCategory: 'グッズ',
    price: '0',
    quantity: 0,
  },
];

export default {
  // getProducts(cb) {
  //   cb(_products);
  // },
  getProducts(cb) {
    setTimeout(() => cb(_products), 100);
  },
  // buyProducts(products, cb, errorCb) {
  //   setTimeout(() => {
  //     // simulate random checkout failure.
  //     Math.random() > 0.5 || navigator.userAgent.indexOf('PhantomJS') > -1 ? cb() : errorCb();
  //   }, 100);
  // },
};
